src/main/java/br/com/estudosjavaee/beans/AdminLivrosBean.java
package br.com.estudosjavaee.beans;

import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.Part;
import javax.transaction.Transactional;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import br.com.estudosjavaee.conf.FacesContextProducer;
import br.com.estudosjavaee.dao.AutorDao;
import br.com.estudosjavaee.dao.LivroDao;
import br.com.estudosjavaee.infra.FileSaver;
import br.com.estudosjavaee.modelo.Autor;
import br.com.estudosjavaee.modelo.Livro;

@Named
@RequestScoped
public class AdminLivrosBean {
	
	private Livro livro = new Livro();
	
	@Inject
	private LivroDao livroDao;
	
	@Inject
	private AutorDao autorDao;
	
	@Inject
	private FacesContext context;
		
	private Part capaLivro;
	
	public FacesContext getContext() {
		return context;
	}

	public void setContext(FacesContext context) {
		this.context = context;
	}

	public Livro getLivro() {
		return livro;
	}

	public void setLivro(Livro livro) {
		this.livro = livro;
	}
		
	public LivroDao getLivroDao() {
		return livroDao;
	}

	public void setLivroDao(LivroDao livroDao) {
		this.livroDao = livroDao;
	}

	public AutorDao getAutorDao() {
		return autorDao;
	}

	public void setAutorDao(AutorDao autorDao) {
		this.autorDao = autorDao;
	}
	
	public Part getCapaLivro() {
		return capaLivro;
	}

	public void setCapaLivro(Part capaLivro) {
		this.capaLivro = capaLivro;
	}

	@Transactional
	public String salvar() throws IOException {

		System.out.println("Livro:" + livro);
		livroDao.salvar(livro);
		FileSaver fileSaver = new FileSaver(); // Nossa nova classe
		livro.setCapaPath(fileSaver.write(capaLivro, "livros")); // Já chamamos o método write e já retornamos o path direto para o Livro		
		
		context = FacesContext.getCurrentInstance();
		context.getExternalContext().getFlash().setKeepMessages(true); //Ativação do Flash Scope
		context.addMessage(null, new FacesMessage("Livro Cadastrado !"));
		
		return "/livros/lista?faces-redirect=true";

	}//salvar
	
	public List<Autor> getAutores(){
		return autorDao.listar();
	}//getAutores
	
	
	
}//class

src/main/java/br/com/estudosjavaee/beans/HomeBean.java
package br.com.estudosjavaee.beans;

import java.util.List;

import javax.enterprise.inject.Model;
import javax.inject.Inject;

import br.com.estudosjavaee.dao.LivroDao;
import br.com.estudosjavaee.modelo.Livro;

@Model
public class HomeBean {
	
	@Inject
	private LivroDao livroDao;
	
	public List<Livro>ultimosLancamentos(){
		return livroDao.ultimosLancamentos();
	}
	
	public List<Livro>demaisLivros(){
		return livroDao.demaisLivros();
	}
	
}

src/main/java/br/com/estudosjavaee/beans/LivroDetalheBean.java
package br.com.estudosjavaee.beans;

import javax.enterprise.inject.Model;
import javax.inject.Inject;

import br.com.estudosjavaee.dao.LivroDao;
import br.com.estudosjavaee.modelo.Livro;

@Model
public class LivroDetalheBean {
	
	@Inject
	private LivroDao livroDao;
	
	private Integer id;
	
	private Livro livro;
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Livro getLivro() {
		return livro;
	}

	public void setLivro(Livro livro) {
		this.livro = livro;
	}

	public void carregarDetalhe() {
		this.livro = livroDao.buscarPorId(id);
	}

}

src/main/java/br/com/estudosjavaee/servlets/FileServlet.java
package br.com.estudosjavaee.servlets;

import java.io.IOException;
import java.net.FileNameMap;
import java.net.URLConnection;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import br.com.estudosjavaee.infra.FileSaver;

@WebServlet("/file/*")
public class FileServlet extends HttpServlet {

    @Override
    protected void service(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
       
    	/*
    	 * Dentro do método service(), conseguimos pegar o que vier pelo * por meio do objeto req.getRequestURI(). 
    	 * O método nos retorna toda a URL, mas só nos interessa o que vier depois de /file, então faremos um split("/file") e 
    	 * do Split teremos dois lados, valor [0] será o que vem antes do /file e [1] o que vem depois. Queremos este último, 
    	 * uma vez que é isso que temos salvo no banco de dados. Desta forma, já teremos o path.    	 */	
    	String path = req.getRequestURI().split("/file")[1];
    	
    	/*
    	 * Podemos juntar o path que temos com o caminho fixo do nosso FileSaver para conseguirmos o caminho completo do arquivo.
    	 *  Passaremos as duas informações para o Paths e assim obtemos um Path como sendo a fonte do nosso arquivo.    	 */
    	Path source = Paths.get(FileSaver.SERVER_PATH + "/" + path);
    	
    	/*
    	 * O Path servirá como fonte para o FileNameMap conseguir chegar no arquivo e obter o contentType. O FileNameMap pode ser
    	 *  obtido usando a classe URLConnection chamando o método estático da classe getFileNameMap.*/
    	FileNameMap fileNameMap = URLConnection.getFileNameMap();
    	
    	/*
    	 * Pelo fileNameMap, chamaremos o método getContentTypeFor() passando nosso source. Só temos antes que informar que o protocolo 
    	 * de acesso é file: para que o FileNameMap possa pegar o arquivo corretamente. Assim sendo, temos:*/
    	String contentType = fileNameMap.getContentTypeFor("file:"+source);
    	
    	res.reset(); //limpar o response para evitar quaisquer dados inválidos
    	res.setContentType(contentType);
    	res.setHeader("Content-Length", String.valueOf(Files.size(source)));
    	res.setHeader("Content-Disposition", "filename=\""+source.getFileName().toString() + "\"");
    	
    	FileSaver.transfer(source, res.getOutputStream());

    }

    
    
    
    
    
}

src/main/webapp/livros/formulario-livro.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	  xmlns:f="http://xmlns.jcp.org/jsf/core"
	  xmlns:h="http://xmlns.jcp.org/jsf/html">

	<!-- <h:messages /> -->
	
	<h:form id="formularioLivro" name="formularioLivro" enctype="multipart/form-data">

		<div>
			<h:outputLabel value="Título"/>
			<h:inputText value="#{adminLivrosBean.livro.titulo}" required="true" id="titulo"/>	
			<h:message for="titulo"/>
		</div>
		<div>
			<h:outputLabel value="Descrição"/>
			<h:inputText rows="4" cols="20" value="#{adminLivrosBean.livro.descricao}" required="true" id="descricao"/>
			<h:message for="descricao"/>	
		</div>
		<div>
			<h:outputLabel value="Número de Páginas"/>
			<h:inputText value="#{adminLivrosBean.livro.numeroPaginas}" required="true" id="numeroDePaginas"/> 	
			<h:message for="numeroDePaginas"/>
		</div>
		<div>
			<h:outputLabel value="Preço"/>
			<h:inputText value="#{adminLivrosBean.livro.preco}" required="true" id="preco"/>
			<h:message for="preco"/>
		</div>
		<div>
		    <h:outputLabel value="Autores" />
		    <h:selectManyListbox value="#{adminLivrosBean.livro.autores}" converter="autorConverter" id="autores">
		        <f:selectItems value="#{adminLivrosBean.autores}"
		         var="autor"
		         itemValue="#{autor}"
		         itemLabel="#{autor.nome}"/>
		    </h:selectManyListbox>
		    <h:message for="autores"/>
		</div>
		
		<div>
			<h:outputLabel value="Capa de Livro"/>
			<h:inputFile value="#{adminLivrosBean.capaLivro}" id="capaLivro"/>
			<h:message for="capaLivro"/>
		</div>
		
		<div>
    		<h:outputLabel value="Data de Publicação" />
    		<h:inputText value="#{adminLivrosBean.livro.dataPublicacao}" id="dataPublicacao" />
			<h:message for="dataPublicacao" />
		</div>
		
		<h:commandButton action="#{adminLivrosBean.salvar}" value="Cadastrar" />
	</h:form>
</html>

src/main/webapp/livros/lista.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
	
	
	
	<h:messages />
	
    <h:dataTable var="livro" value="#{adminListaLivrosBean.livros}">
        <h:column>
            <f:facet name="header">Título</f:facet>
            #{livro.titulo}
        </h:column>
        <h:column>
            <f:facet name="header">Descrição</f:facet>
            #{livro.descricao}
        </h:column>
        <h:column>
            <f:facet name="header">Páginas</f:facet>
            #{livro.numeroPaginas}
        </h:column>
        <h:column>
            <f:facet name="header">Preço</f:facet>
            #{livro.preco}
        </h:column>
        <h:column>
            <f:facet name="header">Autores</f:facet>
            <ui:repeat value="#{livro.autores}" var="autor">
                #{autor.nome},
            </ui:repeat>
        </h:column>
        <h:column>
    <f:facet name="header">Capa Path</f:facet>
    <img src="#{request.contextPath}/file/#{livro.capaPath}" height="30%" alt="#{livro.titulo}" />
</h:column>
	</h:dataTable>
	
	
</html>